{
 "title": "MLOps Metrics (from JSON model) 2022-02",
 "time": { "from": "2022-02-01T00:00:00.000Z", "to": "2022-03-01T00:00:00.000Z" },
 "panels": [
  {
   "title": "Fare - median",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT fare_median, \"timestamp\" FROM metrics"
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns, timestamp AS time FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift, timestamp AS time FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values, timestamp AS time FROM metrics LIMIT 50 "
    }
   ]
  }
 ]
}